project:
  type: website
  output-dir: docs 
website:
  title: "avd"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd 
#      - href: CPI.qmd
#        text: CPI
#      - href: OECD.qmd
#        text: OECD
#      - href: Conclusion.qmd
#        text: Conclusion        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



